/**
 * Scraped Data Loader — Multi-Platform Merge
 * -------------------------------------------
 * Loads listing data from platform-specific JSON files produced by the
 * split scraper workflows, merges them, deduplicates, and reassigns
 * sequential IDs so the rest of the app sees a single unified dataset.
 *
 * Load order (each file is optional — missing files are silently skipped):
 *   scraped-listings-fast.json   → BidSpotter + HiBid (updated every 2 h)
 *   scraped-listings-estate.json → EstateSales.NET + MaxSold + Proxibid (every 8 h)
 *   scraped-listings-ebay.json   → eBay sold comps + 1stDibs (daily)
 *   scraped-listings.json        → Legacy full-national run (daily fallback)
 *
 * Falls back to the 24-item mock dataset only when ALL files are absent.
 *
 * IMPORTANT: each require() call MUST use a literal string — webpack can only
 * statically analyse and bundle JSON when the path is a compile-time constant.
 * A variable path like require(filePath) silently fails to bundle.
 *
 * MUST NOT be imported from client components.
 */

import { LISTINGS as MOCK_LISTINGS, type MockListing } from "@/app/api/v1/_mock-data";

// City-string patterns that are placeholder text, not real place names.
const GARBAGE_CITY_RE =
  /see description|check description|call for|tbd|t\.b\.d|varies|multiple locations|various locations|see listing|see details|nationwide|pick up only|no location|not specified|please read|see auction|location tba/i;

// Off-topic titles that slipped through the scraper-level filter.
const GARBAGE_TITLE_RE =
  /\b(van clearance|site closure|site clearance|liquidation sale|clearance auction|vehicle auction|car auction|truck auction|fleet auction|auto auction|plant hire|pallet lot|truckload)\b/i;

function isMeaningful(listing: MockListing): boolean {
  if (!listing.external_url?.startsWith("http")) return false;
  if (!listing.title?.trim()) return false;
  if (GARBAGE_TITLE_RE.test(listing.title)) return false;
  // Drop auctions that ended > 60 days ago and were never marked completed
  if (listing.sale_ends_at && !listing.is_completed) {
    const ended = new Date(listing.sale_ends_at).getTime();
    if (!isNaN(ended) && ended < Date.now() - 60 * 24 * 60 * 60 * 1000) return false;
  }
  return true;
}

function cleanListing(listing: MockListing): MockListing {
  if (listing.city && GARBAGE_CITY_RE.test(listing.city)) {
    return { ...listing, city: null, latitude: null, longitude: null };
  }
  return listing;
}

function tryLoad(loader: () => unknown): MockListing[] {
  try {
    const data = loader();
    if (Array.isArray(data) && data.length > 0) return data as MockListing[];
  } catch {
    // File not yet generated by scraper CI — skip silently
  }
  return [];
}

function loadAllListings(): MockListing[] {
  // Each require() uses a LITERAL string so webpack can statically bundle the files.
  // Do NOT refactor these into a loop with a variable path — that breaks bundling.
  const raw: MockListing[] = [
    ...tryLoad(() => require("@/data/scraped-listings-fast.json")),
    ...tryLoad(() => require("@/data/scraped-listings-estate.json")),
    ...tryLoad(() => require("@/data/scraped-listings-ebay.json")),
    ...tryLoad(() => require("@/data/scraped-listings.json")),
  ];

  if (raw.length === 0) return MOCK_LISTINGS;

  const seen = new Set<string>();
  const merged: MockListing[] = [];
  let nextId = 1;

  for (const listing of raw) {
    const key = `${listing.platform?.name ?? "unknown"}:${listing.external_id ?? listing.id}`;
    if (seen.has(key)) continue;
    seen.add(key);

    const cleaned = cleanListing(listing);
    if (!isMeaningful(cleaned)) continue;

    merged.push({ ...cleaned, id: nextId++ });
  }

  // Still nothing after filtering? Fall back to mock so the page isn't blank.
  return merged.length > 0 ? merged : MOCK_LISTINGS;
}

const _data: MockListing[] = loadAllListings();

export function getListings(): MockListing[] {
  return _data;
}
