/**
 * Scraped Data Loader — Multi-Platform Merge
 * -------------------------------------------
 * Loads listing data from platform-specific JSON files produced by the
 * split scraper workflows, merges them, deduplicates, and reassigns
 * sequential IDs so the rest of the app sees a single unified dataset.
 *
 * Load order (each file is optional — missing files are silently skipped):
 *   scraped-listings-fast.json   → BidSpotter + HiBid (updated every 2 h)
 *   scraped-listings-estate.json → EstateSales.NET + MaxSold + Proxibid (every 8 h)
 *   scraped-listings-ebay.json   → eBay sold comps + 1stDibs (daily)
 *   scraped-listings.json        → Legacy full-national run (daily fallback)
 *
 * Falls back to the 24-item mock dataset only when ALL files are absent.
 *
 * Uses require() so webpack bundles the JSON at build time — this works
 * correctly on Vercel serverless (unlike fs.readFileSync).
 *
 * MUST NOT be imported from client components.
 */

import { LISTINGS as MOCK_LISTINGS, type MockListing } from "@/app/api/v1/_mock-data";

// Platform-specific files, in merge order (fast data first so it's seen first
// when IDs are deduplicated, keeping the most frequently refreshed data).
const PLATFORM_FILES = [
  "@/data/scraped-listings-fast.json",
  "@/data/scraped-listings-estate.json",
  "@/data/scraped-listings-ebay.json",
  "@/data/scraped-listings.json",        // legacy / full-national fallback
] as const;

// City-string patterns that are placeholder text, not real place names.
// Scrapers sometimes copy these verbatim from listing description fields.
const GARBAGE_CITY_RE = /see description|check description|call for|tbd|t\.b\.d|varies|multiple locations|various locations|see listing|see details|nationwide|pick up only|no location|not specified|please read|see auction|location tba/i;

// Titles that clearly indicate non-antique / non-estate-sale content that
// slipped past the Python-level filter (e.g. stale JSON from before the fix).
const GARBAGE_TITLE_RE = /\b(van clearance|site closure|site clearance|liquidation sale|clearance auction|vehicle auction|car auction|truck auction|fleet auction|auto auction|plant hire|pallet lot|truckload)\b/i;

/**
 * Return true if the listing has enough real data to be worth displaying.
 * Frontend safety net — the scraper filter handles most cases at generation
 * time; this catches anything that slipped through in cached/stale JSON.
 */
function isMeaningful(listing: MockListing): boolean {
  // Must have a real destination URL — without it every CTA is broken
  if (!listing.external_url?.startsWith("http")) return false;

  // Must have a non-empty title
  if (!listing.title?.trim()) return false;

  // Reject off-topic titles that shouldn't have made it through
  if (GARBAGE_TITLE_RE.test(listing.title)) return false;

  // Skip listings that ended > 60 days ago and were never marked completed
  // (stale auction records with no results that will never update)
  if (listing.sale_ends_at && !listing.is_completed) {
    const ended = new Date(listing.sale_ends_at).getTime();
    if (!isNaN(ended) && ended < Date.now() - 60 * 24 * 60 * 60 * 1000) return false;
  }

  return true;
}

/**
 * Nullify known-garbage location strings so they don't reach the map,
 * proximity filter, or city display.  Real city names won't match.
 */
function cleanListing(listing: MockListing): MockListing {
  if (listing.city && GARBAGE_CITY_RE.test(listing.city)) {
    return { ...listing, city: null, latitude: null, longitude: null };
  }
  return listing;
}

function loadAllListings(): MockListing[] {
  const raw: MockListing[] = [];

  for (const filePath of PLATFORM_FILES) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const data: unknown = require(filePath);
      if (Array.isArray(data) && data.length > 0) {
        raw.push(...(data as MockListing[]));
      }
    } catch {
      // File not yet generated by CI — skip silently
    }
  }

  if (raw.length === 0) return MOCK_LISTINGS;

  // Deduplicate by platform + external_id (handles overlap between full and
  // platform-specific files), then reassign sequential integer IDs so the
  // rest of the app can use listing.id for routing safely.
  const seen = new Set<string>();
  const merged: MockListing[] = [];
  let nextId = 1;

  for (const raw_listing of raw) {
    const listing = raw_listing as MockListing;
    const key = `${listing.platform?.name ?? "unknown"}:${listing.external_id ?? listing.id}`;
    if (seen.has(key)) continue;
    seen.add(key);

    const cleaned = cleanListing(listing);
    if (!isMeaningful(cleaned)) continue;

    merged.push({ ...cleaned, id: nextId++ });
  }

  return merged;
}

// Evaluate once at module load (happens at build time on Vercel).
const _data: MockListing[] = loadAllListings();

export function getListings(): MockListing[] {
  return _data;
}
