/**
 * Scraped Data Loader — Multi-Platform Merge
 * -------------------------------------------
 * Loads listing data from platform-specific JSON files produced by the
 * split scraper workflows, merges them, deduplicates, and reassigns
 * sequential IDs so the rest of the app sees a single unified dataset.
 *
 * Load order (each file is optional — missing files are silently skipped):
 *   scraped-listings-fast.json   → BidSpotter + HiBid (updated every 2 h)
 *   scraped-listings-estate.json → EstateSales.NET + MaxSold + Proxibid (every 8 h)
 *   scraped-listings-ebay.json   → eBay sold comps + 1stDibs (daily)
 *   scraped-listings.json        → Legacy full-national run (daily fallback)
 *
 * Falls back to the 24-item mock dataset only when ALL files are absent.
 *
 * Uses require() so webpack bundles the JSON at build time — this works
 * correctly on Vercel serverless (unlike fs.readFileSync).
 *
 * MUST NOT be imported from client components.
 */

import { LISTINGS as MOCK_LISTINGS, type MockListing } from "@/app/api/v1/_mock-data";

// Platform-specific files, in merge order (fast data first so it's seen first
// when IDs are deduplicated, keeping the most frequently refreshed data).
const PLATFORM_FILES = [
  "@/data/scraped-listings-fast.json",
  "@/data/scraped-listings-estate.json",
  "@/data/scraped-listings-ebay.json",
  "@/data/scraped-listings.json",        // legacy / full-national fallback
] as const;

function loadAllListings(): MockListing[] {
  const raw: MockListing[] = [];

  for (const filePath of PLATFORM_FILES) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const data: unknown = require(filePath);
      if (Array.isArray(data) && data.length > 0) {
        raw.push(...(data as MockListing[]));
      }
    } catch {
      // File not yet generated by CI — skip silently
    }
  }

  if (raw.length === 0) return MOCK_LISTINGS;

  // Deduplicate by platform + external_id (handles overlap between full and
  // platform-specific files), then reassign sequential integer IDs so the
  // rest of the app can use listing.id for routing safely.
  const seen = new Set<string>();
  const merged: MockListing[] = [];
  let nextId = 1;

  for (const listing of raw) {
    const key = `${listing.platform?.name ?? "unknown"}:${listing.external_id ?? listing.id}`;
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push({ ...listing, id: nextId++ });
  }

  return merged;
}

// Evaluate once at module load (happens at build time on Vercel).
const _data: MockListing[] = loadAllListings();

export function getListings(): MockListing[] {
  return _data;
}
